In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression, ElasticNet,Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold,cross_val_score,cross_val_predict, cross_validate,GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import warnings
from tqdm import tqdm
import os
os.chdir("/home/pgcp-ai/MachineLearning/Cases/Concrete_Strength/")

In [43]:
concrete = pd.read_csv("Concrete_Data.csv")
concrete

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77


In [44]:
X, y = concrete.drop("Strength", axis = 1), concrete["Strength"]

In [4]:
lr = LinearRegression()
kfold = KFold(n_splits=5,shuffle=True,random_state=26)
results = cross_val_score(lr,X,y,cv=kfold)
print(results)
print(np.mean(results))

[0.61474372 0.56604898 0.59335131 0.61186382 0.62837728]
0.602877022245518


In [5]:
y_pred = cross_val_predict(lr,X,y)
y_pred

array([52.91102666, 53.27074566, 59.0714751 , ..., 27.00030254,
       30.04053931, 31.94216984])

In [6]:
cross_validate(lr, X, y)

{'fit_time': array([0.00479102, 0.0037415 , 0.00293708, 0.00267768, 0.00281382]),
 'score_time': array([0.00289989, 0.00276446, 0.00199056, 0.00274968, 0.00225115]),
 'test_score': array([0.33015205, 0.41207076, 0.45175533, 0.60725028, 0.50374183])}

In [16]:
alphas = np.linspace(0.001, 10, 30)
scores = []
folds = KFold(n_splits = 5, shuffle = True, random_state = 26)

for a in tqdm(alphas):
    ridge = Ridge(alpha = a)
    score = cross_val_score(ridge, X, y, cv=folds)
    print(score)
    scores.append([a, np.mean(score)])
    
df_scores = pd.DataFrame(scores, columns = ["Alpha", "Cross Validation Score"])
df_scores.sort_values("Cross Validation Score", ascending = False)

 30%|█████████████▏                              | 9/30 [00:00<00:00, 40.42it/s]

[0.61474372 0.56604898 0.59335131 0.61186383 0.62837728]
[0.61474377 0.56604882 0.59335126 0.61186417 0.62837729]
[0.61474383 0.56604866 0.59335121 0.61186452 0.62837729]
[0.61474389 0.5660485  0.59335115 0.61186486 0.6283773 ]
[0.61474395 0.56604835 0.5933511  0.61186521 0.6283773 ]
[0.61474401 0.56604819 0.59335105 0.61186555 0.62837731]
[0.61474406 0.56604803 0.593351   0.6118659  0.62837731]
[0.61474412 0.56604787 0.59335094 0.61186624 0.62837732]
[0.61474418 0.56604772 0.59335089 0.61186659 0.62837732]


 47%|████████████████████                       | 14/30 [00:00<00:00, 41.00it/s]

[0.61474424 0.56604756 0.59335084 0.61186693 0.62837733]
[0.6147443  0.5660474  0.59335079 0.61186728 0.62837734]
[0.61474435 0.56604724 0.59335073 0.61186762 0.62837734]
[0.61474441 0.56604708 0.59335068 0.61186797 0.62837735]
[0.61474447 0.56604693 0.59335063 0.61186831 0.62837735]
[0.61474453 0.56604677 0.59335058 0.61186866 0.62837736]
[0.61474459 0.56604661 0.59335053 0.611869   0.62837736]
[0.61474464 0.56604645 0.59335047 0.61186935 0.62837737]
[0.6147447  0.56604629 0.59335042 0.61186969 0.62837737]


 80%|██████████████████████████████████▍        | 24/30 [00:00<00:00, 41.76it/s]

[0.61474476 0.56604614 0.59335037 0.61187004 0.62837738]
[0.61474482 0.56604598 0.59335032 0.61187038 0.62837738]
[0.61474488 0.56604582 0.59335026 0.61187073 0.62837739]
[0.61474493 0.56604566 0.59335021 0.61187107 0.62837739]
[0.61474499 0.56604551 0.59335016 0.61187142 0.6283774 ]
[0.61474505 0.56604535 0.59335011 0.61187176 0.6283774 ]
[0.61474511 0.56604519 0.59335005 0.61187211 0.62837741]
[0.61474516 0.56604503 0.59335    0.61187245 0.62837741]
[0.61474522 0.56604488 0.59334995 0.61187279 0.62837742]


100%|███████████████████████████████████████████| 30/30 [00:00<00:00, 40.97it/s]

[0.61474528 0.56604472 0.5933499  0.61187314 0.62837742]
[0.61474534 0.56604456 0.59334984 0.61187348 0.62837743]
[0.6147454  0.5660444  0.59334979 0.61187383 0.62837743]


,Alpha,Cross Validation Score
29,10.000000,0.602878
28,9.655207,0.602878
27,9.310414,0.602878
26,8.965621,0.602878
25,8.620828,0.602878
24,8.276034,0.602878
23,7.931241,0.602878
22,7.586448,0.602878
21,7.241655,0.602878
20,6.896862,0.602878


In [17]:
alphas = np.linspace(0.001, 10, 30)
ratios = np.linspace(0.001, 1, 10)
scores = []
folds = KFold(n_splits = 5, shuffle = True, random_state = 26)

for a in tqdm(alphas):
    for r in ratios:
        el = ElasticNet(alpha = a, l1_ratio = r)
        score = cross_val_score(el, X, y, cv=folds)
#         print(score)
        scores.append([a, np.mean(score)])
    
df_scores = pd.DataFrame(scores, columns = ["Alpha", "Cross Validation Score"])
df_scores.sort_values("Cross Validation Score", ascending = False)

100%|███████████████████████████████████████████| 30/30 [00:07<00:00,  3.77it/s]


,Alpha,Cross Validation Score
80,2.759345,0.602982
70,2.414552,0.602981
90,3.104138,0.602981
100,3.448931,0.602978
60,2.069759,0.602977
...,...,...
269,8.965621,0.598299
298,10.000000,0.598284
279,9.310414,0.598207
289,9.655207,0.598110


In [18]:
alphas = np.linspace(0.001, 10, 30)
ratios = np.linspace(0.001, 1, 10)
scores = []
folds = KFold(n_splits = 5, shuffle = True, random_state = 26)

for a in tqdm(alphas):
    for r in ratios:
        el = ElasticNet(alpha = a, l1_ratio = r)
        score = cross_val_score(el, X, y, cv=folds,scoring='neg_root_mean_squared_error')
#         print(score)
        scores.append([a, np.mean(score)])
    
df_scores = pd.DataFrame(scores, columns = ["Alpha", "Cross Validation Score"])
df_scores.sort_values("Cross Validation Score", ascending = False)

100%|███████████████████████████████████████████| 30/30 [00:07<00:00,  3.96it/s]


,Alpha,Cross Validation Score
90,3.104138,-10.456384
100,3.448931,-10.456385
80,2.759345,-10.456410
110,3.793724,-10.456410
120,4.138517,-10.456456
...,...,...
269,8.965621,-10.515979
298,10.000000,-10.516177
279,9.310414,-10.517215
289,9.655207,-10.518506


In [21]:
max_features = np.arange(1,len(X.columns)+1)
scores = []
folds = KFold(n_splits = 5, shuffle = True, random_state = 26)

for m in tqdm(max_features):
    
    rf = RandomForestRegressor(max_features=m,random_state=26)
    score = cross_val_score(rf, X, y, cv=folds,scoring='neg_root_mean_squared_error')
#         print(score)
    scores.append([m, np.mean(score)])
    
df_scores = pd.DataFrame(scores, columns = ["Maximum Features", "Cross Validation Score"])
df_scores.sort_values("Cross Validation Score", ascending = False)

100%|█████████████████████████████████████████████| 8/8 [00:12<00:00,  1.59s/it]


,Maximum Features,Cross Validation Score
3,4,-4.751942
4,5,-4.754536
5,6,-4.790249
2,3,-4.794503
6,7,-4.814700
7,8,-4.876792
1,2,-5.088724
0,1,-6.169725


In [59]:
kfold = KFold(n_splits = 5, shuffle = True, random_state = 26)
max_features = [2,3,4,5,6,7]
params = {'max_features' : max_features}
rf = RandomForestRegressor(random_state=26)
gcv = GridSearchCV(estimator=rf,param_grid=params,cv=kfold,scoring='neg_root_mean_squared_error',n_jobs = -1, verbose=3)
gcv.fit(X,y)
gcv.best_score_,gcv.best_params_

Fitting 5 folds for each of 6 candidates, totalling 30 fits


(-4.751942056038116, {'max_features': 4})

[CV 4/5] END ...................max_features=4;, score=-5.723 total time=   0.6s
[CV 1/5] END ...................max_features=5;, score=-5.686 total time=   0.7s
[CV 2/5] END ...................max_features=2;, score=-4.679 total time=   0.4s
[CV 2/5] END ...................max_features=5;, score=-4.122 total time=   0.6s
[CV 1/5] END ...................max_features=2;, score=-6.111 total time=   0.4s
[CV 3/5] END ...................max_features=5;, score=-4.276 total time=   0.6s
[CV 3/5] END ...................max_features=2;, score=-4.431 total time=   0.4s
[CV 4/5] END ...................max_features=5;, score=-5.701 total time=   0.6s
[CV 5/5] END ...................max_features=2;, score=-4.112 total time=   0.4s
[CV 5/5] END ...................max_features=5;, score=-3.988 total time=   0.6s
[CV 4/5] END ...................max_features=2;, score=-6.111 total time=   0.4s
[CV 1/5] END ...................max_features=6;, score=-5.588 total time=   0.6s
[CV 2/5] END ...............

In [61]:
os.chdir("/home/pgcp-ai/MachineLearning/Datasets/")

In [62]:
housing = pd.read_csv("Housing.csv")
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no


In [63]:
X,y = housing.drop('price',axis=1),housing['price']

In [67]:
ohe = OneHotEncoder(drop = 'first', handle_unknown = 'ignore')
transformer = ColumnTransformer(transformers = [('OHE', ohe, make_column_selector(dtype_include = object))]
                               , remainder='passthrough', verbose_feature_names_out=False)

In [26]:
max_features = [2,3,4,5,6,7]
scores = []
folds = KFold(n_splits = 5, shuffle = True, random_state = 26)

for m in tqdm(max_features):
    rf = RandomForestRegressor(max_features=m,random_state=26)
    pipe = Pipeline([('OHE',transformer),('RF',rf)])
    score = cross_val_score(pipe, X, y, cv=folds,scoring='neg_root_mean_squared_error')
#         print(score)
    scores.append([m,np.mean(score)])
    
df_scores = pd.DataFrame(scores, columns = ["Maximum Features", "Cross Validation Score"])
df_scores.sort_values("Cross Validation Score", ascending = False)

100%|█████████████████████████████████████████████| 6/6 [00:04<00:00,  1.21it/s]


,Maximum Features,Cross Validation Score
1,3,-16204.207742
0,2,-16284.461884
3,5,-16338.488053
2,4,-16530.071722
4,6,-16686.581621
5,7,-16759.855179


In [45]:
kfold = KFold(n_splits = 5, shuffle = True, random_state = 26)

In [46]:
alphas = np.linspace(0.001,10,30)
params = {'alpha' : alphas}
ridge = Ridge()
gcv = GridSearchCV(estimator=ridge,param_grid=params,cv=kfold)

In [48]:
gcv.fit(X,y)

GridSearchCV(cv=KFold(n_splits=5, random_state=26, shuffle=True),
             estimator=Ridge(),
             param_grid={'alpha': array([1.00000000e-03, 3.45793103e-01, 6.90586207e-01, 1.03537931e+00,
       1.38017241e+00, 1.72496552e+00, 2.06975862e+00, 2.41455172e+00,
       2.75934483e+00, 3.10413793e+00, 3.44893103e+00, 3.79372414e+00,
       4.13851724e+00, 4.48331034e+00, 4.82810345e+00, 5.17289655e+00,
       5.51768966e+00, 5.86248276e+00, 6.20727586e+00, 6.55206897e+00,
       6.89686207e+00, 7.24165517e+00, 7.58644828e+00, 7.93124138e+00,
       8.27603448e+00, 8.62082759e+00, 8.96562069e+00, 9.31041379e+00,
       9.65520690e+00, 1.00000000e+01])})

In [49]:
pd_cv = pd.DataFrame(gcv.cv_results_)
pd_cv

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003840,0.001432,0.002595,0.000614,0.001,{'alpha': 0.001},0.614744,0.566049,0.593351,0.611864,0.628377,0.602877,0.021535,30
1,0.002327,0.000292,0.001958,0.000146,0.345793,{'alpha': 0.3457931034482759},0.614744,0.566049,0.593351,0.611864,0.628377,0.602877,0.021536,29
2,0.002224,0.000285,0.001810,0.000026,0.690586,{'alpha': 0.6905862068965518},0.614744,0.566049,0.593351,0.611865,0.628377,0.602877,0.021536,28
3,0.001965,0.000027,0.001714,0.000034,1.035379,{'alpha': 1.0353793103448277},0.614744,0.566049,0.593351,0.611865,0.628377,0.602877,0.021536,27
4,0.001974,0.000056,0.001694,0.000046,1.380172,{'alpha': 1.3801724137931035},0.614744,0.566048,0.593351,0.611865,0.628377,0.602877,0.021536,26
5,0.001946,0.000045,0.001679,0.000008,1.724966,{'alpha': 1.7249655172413794},0.614744,0.566048,0.593351,0.611866,0.628377,0.602877,0.021536,25
6,0.001999,0.000088,0.001692,0.000050,2.069759,{'alpha': 2.0697586206896554},0.614744,0.566048,0.593351,0.611866,0.628377,0.602877,0.021536,24
7,0.002042,0.000142,0.001655,0.000100,2.414552,{'alpha': 2.4145517241379313},0.614744,0.566048,0.593351,0.611866,0.628377,0.602877,0.021536,23
8,0.001993,0.000073,0.001675,0.000010,2.759345,{'alpha': 2.759344827586207},0.614744,0.566048,0.593351,0.611867,0.628377,0.602877,0.021536,22
9,0.002071,0.000071,0.001681,0.000028,3.104138,{'alpha': 3.104137931034483},0.614744,0.566048,0.593351,0.611867,0.628377,0.602877,0.021536,21


In [50]:
gcv.best_params_,gcv.best_score_

({'alpha': 10.0}, 0.6028781702961167)

In [53]:
params = {'alpha':np.linspace(0.001, 10, 30), 'l1_ratio':np.linspace(0.001, 1, 10)}
el = ElasticNet()
gcv = GridSearchCV(estimator = el, param_grid=params, cv = kfold)
gcv.fit(X, y)
gcv.best_params_, gcv.best_score_

({'alpha': 2.759344827586207, 'l1_ratio': 0.001}, 0.6029818143707282)

In [54]:
pd.DataFrame(gcv.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006234,0.001763,0.002548,0.000497,0.001,0.001,"{'alpha': 0.001, 'l1_ratio': 0.001}",0.614744,0.566049,0.593351,0.611865,0.628377,0.602877,0.021536,36
1,0.004324,0.000140,0.004118,0.003869,0.001,0.112,"{'alpha': 0.001, 'l1_ratio': 0.112}",0.614744,0.566048,0.593351,0.611865,0.628377,0.602877,0.021536,37
2,0.004454,0.000242,0.002201,0.000162,0.001,0.223,"{'alpha': 0.001, 'l1_ratio': 0.223}",0.614744,0.566048,0.593351,0.611865,0.628377,0.602877,0.021536,38
3,0.004146,0.000232,0.002069,0.000190,0.001,0.334,"{'alpha': 0.001, 'l1_ratio': 0.334}",0.614744,0.566048,0.593351,0.611865,0.628377,0.602877,0.021536,39
4,0.004337,0.000145,0.002148,0.000179,0.001,0.445,"{'alpha': 0.001, 'l1_ratio': 0.445}",0.614744,0.566048,0.593351,0.611865,0.628377,0.602877,0.021536,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.002917,0.000132,0.002033,0.000146,10.0,0.556,"{'alpha': 10.0, 'l1_ratio': 0.556}",0.612817,0.556761,0.587081,0.615438,0.622985,0.599016,0.024342,263
296,0.002194,0.000082,0.001783,0.000045,10.0,0.667,"{'alpha': 10.0, 'l1_ratio': 0.667}",0.612569,0.556731,0.586793,0.615122,0.622569,0.598757,0.024228,280
297,0.002212,0.000163,0.001726,0.000055,10.0,0.778,"{'alpha': 10.0, 'l1_ratio': 0.778}",0.612374,0.556673,0.586614,0.614872,0.622121,0.598531,0.024122,290
298,0.002154,0.000071,0.001704,0.000009,10.0,0.889,"{'alpha': 10.0, 'l1_ratio': 0.889}",0.612157,0.556588,0.586421,0.614591,0.621663,0.598284,0.024018,297


In [70]:
X,y = housing.drop('price',axis=1),housing['price']
rf = RandomForestRegressor(random_state = 26)
pipe = Pipeline([('OHE', transformer), ('RF', rf)])
params = {"RF__max_features" : [2,3,4,5,6,7]}
kfold = KFold(n_splits = 5, shuffle = True, random_state = 26)
gcv = GridSearchCV(estimator = pipe, param_grid=params, cv = kfold,n_jobs=-1, scoring ='neg_root_mean_squared_error')
gcv.fit(X, y)
gcv.best_params_, gcv.best_score_

({'RF__max_features': 3}, -16204.207742358189)