In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, precision_score, recall_score, classification_report
import os
os.chdir('/home/pgcp-ai/MachineLearning/Datasets')

In [ ]:
sonar = pd.read_csv('Sonar.csv')
X, y = sonar.drop('Class', axis = 1), sonar['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26, stratify = sonar['Class'])

lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred_prob = lr.predict_proba(X_test)
y_pred_prob

array([[0.35532582, 0.64467418],
       [0.59480049, 0.40519951],
       [0.63752692, 0.36247308],
       [0.31115444, 0.68884556],
       [0.48792708, 0.51207292],
       [0.58155164, 0.41844836],
       [0.4559988 , 0.5440012 ],
       [0.22340494, 0.77659506],
       [0.24148414, 0.75851586],
       [0.44055728, 0.55944272],
       [0.47809684, 0.52190316],
       [0.78109377, 0.21890623],
       [0.75963459, 0.24036541],
       [0.96666099, 0.03333901],
       [0.45513684, 0.54486316],
       [0.60376445, 0.39623555],
       [0.23689547, 0.76310453],
       [0.94858708, 0.05141292],
       [0.8794644 , 0.1205356 ],
       [0.25589784, 0.74410216],
       [0.79068207, 0.20931793],
       [0.23353374, 0.76646626],
       [0.11901415, 0.88098585],
       [0.74102041, 0.25897959],
       [0.34086996, 0.65913004],
       [0.25592566, 0.74407434],
       [0.96790757, 0.03209243],
       [0.9151953 , 0.0848047 ],
       [0.72973532, 0.27026468],
       [0.60440165, 0.39559835],
       [0.

In [ ]:
np.argmax(y_pred_prob, axis = 1)

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1])

In [ ]:
lr.predict(X_test)

array(['R', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'R', 'R', 'R', 'M', 'M',
       'M', 'R', 'M', 'R', 'M', 'M', 'R', 'M', 'R', 'R', 'M', 'R', 'R',
       'M', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'R', 'R', 'R', 'M', 'R',
       'M', 'M', 'M', 'R', 'R', 'R', 'M', 'R', 'M', 'R', 'M', 'M', 'M',
       'R', 'M', 'M', 'M', 'M', 'M', 'R', 'R', 'R', 'M', 'R'],
      dtype=object)

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
pd.crosstab(y_test, y_pred)

col_0,M,R
Class,,
M,28,6
R,4,25


In [ ]:
confusion_matrix(y_test, y_pred)

array([[28,  6],
       [ 4, 25]])

In [ ]:
print(recall_score(y_test, y_pred, pos_label='M'))
print(recall_score(y_test, y_pred, pos_label='R'))

0.8235294117647058
0.8620689655172413


In [ ]:
print(precision_score(y_test, y_pred, pos_label='M'))
print(precision_score(y_test, y_pred, pos_label='R'))

0.875
0.8064516129032258


In [ ]:
print(f1_score(y_test, y_pred, pos_label='M'))
print(f1_score(y_test, y_pred, pos_label='R'))

0.8484848484848485
0.8333333333333334


In [ ]:
f1_score(y_test, y_pred, average = 'macro')

0.8409090909090909

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           M       0.88      0.82      0.85        34
           R       0.81      0.86      0.83        29

    accuracy                           0.84        63
   macro avg       0.84      0.84      0.84        63
weighted avg       0.84      0.84      0.84        63



In [ ]:
y.value_counts()

Class
M    111
R     97
Name: count, dtype: int64

In [ ]:
import sklearn

In [ ]:
sklearn.__version__

'1.3.2'

In [ ]:
!pip install -U scikit-learn

Requirement already up-to-date: scikit-learn in /home/pgcp-ai/.local/lib/python3.8/site-packages (1.3.2)


In [ ]:
sklearn.__version__

'1.3.2'

In [ ]:
solvers=['lbfgs','liblinear','newton-cg','newton-cholesky','sag','saga']
Cs = np.linspace(0.001,5,20)
scores = []
for s in solvers:
    for c in Cs:
        lr = LogisticRegression(solver=s,C=c,max_iter=500)
        lr.fit(X_train,y_train)
        y_pred = lr.predict(X_test)
        scores.append([s,c,f1_score(y_test,y_pred,average='macro')])


In [ ]:
df_scores = pd.DataFrame(scores,columns=['Solver','C','Score'])

In [ ]:
df_scores.sort_values('Score',ascending=False)

,Solver,C,Score
85,sag,1.316526,0.840909
106,saga,1.579632,0.840909
82,sag,0.527211,0.840909
84,sag,1.053421,0.840909
83,sag,0.790316,0.840909
...,...,...,...
100,saga,0.001000,0.350515
80,sag,0.001000,0.350515
40,newton-cg,0.001000,0.350515
20,liblinear,0.001000,0.350515
