In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.linspace(-10,10)
x

array([-10.        ,  -9.59183673,  -9.18367347,  -8.7755102 ,
        -8.36734694,  -7.95918367,  -7.55102041,  -7.14285714,
        -6.73469388,  -6.32653061,  -5.91836735,  -5.51020408,
        -5.10204082,  -4.69387755,  -4.28571429,  -3.87755102,
        -3.46938776,  -3.06122449,  -2.65306122,  -2.24489796,
        -1.83673469,  -1.42857143,  -1.02040816,  -0.6122449 ,
        -0.20408163,   0.20408163,   0.6122449 ,   1.02040816,
         1.42857143,   1.83673469,   2.24489796,   2.65306122,
         3.06122449,   3.46938776,   3.87755102,   4.28571429,
         4.69387755,   5.10204082,   5.51020408,   5.91836735,
         6.32653061,   6.73469388,   7.14285714,   7.55102041,
         7.95918367,   8.36734694,   8.7755102 ,   9.18367347,
         9.59183673,  10.        ])

In [3]:
y = 3*x + 5
y

array([-25.        , -23.7755102 , -22.55102041, -21.32653061,
       -20.10204082, -18.87755102, -17.65306122, -16.42857143,
       -15.20408163, -13.97959184, -12.75510204, -11.53061224,
       -10.30612245,  -9.08163265,  -7.85714286,  -6.63265306,
        -5.40816327,  -4.18367347,  -2.95918367,  -1.73469388,
        -0.51020408,   0.71428571,   1.93877551,   3.16326531,
         4.3877551 ,   5.6122449 ,   6.83673469,   8.06122449,
         9.28571429,  10.51020408,  11.73469388,  12.95918367,
        14.18367347,  15.40816327,  16.63265306,  17.85714286,
        19.08163265,  20.30612245,  21.53061224,  22.75510204,
        23.97959184,  25.20408163,  26.42857143,  27.65306122,
        28.87755102,  30.10204082,  31.32653061,  32.55102041,
        33.7755102 ,  35.        ])

In [4]:
sum_xy = np.sum(x*y)
sum_xy

5204.081632653061

In [5]:
n = len(x)

In [6]:
x_bar,y_bar = np.mean(x),np.mean(y)
x_bar,y_bar

(1.4210854715202004e-16, 5.000000000000001)

In [7]:
sum_x2 = np.sum(x**2)

In [8]:
b1 = ((sum_xy/n) - (x_bar*y_bar))/((sum_x2/n) - (x_bar**2))
b0 = y_bar-b1*x_bar
b0,b1

(5.000000000000001, 2.9999999999999996)

In [9]:
lr = LinearRegression()
lr.fit(x.reshape(-1,1),y)

LinearRegression()

In [10]:
lr.coef_,lr.intercept_

(array([3.]), 5.000000000000001)

In [11]:
lr.fit?